package com.example.employeeLeaveApplication.enums;

public enum EventType {
    LEAVE_APPLIED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    MEETING_REQUIRED,
    LEAVE_CANCELLED,
    LEAVE_IN_PROGRESS,
    LOW_LEAVE_BALANCE,
    PENDING_LEAVE_REMINDER,
    PROFILE_SUBMITTED,
    PROFILE_VERIFIED,
    PROFILE_REJECTED,
    LOP_CONFIRMATION_REQUIRED,
    ACCESS_REQUEST_SUBMITTED,
    ACCESS_REQUEST_MANAGER_APPROVED,
    ACCESS_REQUEST_MANAGER_REJECTED,
    ACCESS_REQUEST_ADMIN_APPROVED,
    ACCESS_REQUEST_ADMIN_REJECTED,
    OD_APPLIED,
    OD_APPROVED,
    OD_REJECTED,
    OD_CANCELLED,
    OD_IN_PROGRESS
}
