spring.application.name=notification-service

spring.datasource.url=jdbc:mysql://localhost:3306/notification_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crazyyy1235@gmail.com
spring.mail.password=imykcmhruasqcxkw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#app.server.ip=192.168.1.62
#app.server.port=9090
app.server.ip=0.0.0.0
app.server.port=8080

spring.jackson.serialization.fail-on-empty-beans=false

jwt.secret=8f7d9c2a6e1b4c9d8f7d9c2a6e1b4c9d
jwt.expiration=86400000

file.upload-dir=uploads/leaves
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

